name: CI/CD Deplay

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      # 切换到master分支
      - name: checkout
        uses: actions/checkout@master
      # 使用 node: 12
      - name: setup-node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      # 安装
      - name: npm install
        run: npm install
      # 构建
      - name: npm build
        run: npm run docs:build
      # 部署
      - name: deploy
        run: npm run deploy
        # 注入环境变量供ssh-deploy使用
        env:
          # secrets中配置的私钥，用于免密连接服务器
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          # 服务器地址
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          # 用户名
          REMOTE_USER: ${{ secrets.REMOTE_USER }}