name: CI/CD Deplay

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 15.x]
    steps:
      # 切换到master分支
      - uses: actions/checkout@master
      # 使用 node:10
      - name: Use Node.js
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      # 部署
      - name: deploy
        run: npm run deploy
        env: